Repository Northeastern-Electric-Racing/PM-Dashboard-v1, pull requests merged in 2020-10, with the labels that each got.

#9 added issue tracking explanation to readme
  README.md
Labels: documentation

#21 Reformatted Change Request for Reports Tab
  Code.js
  Stylesheet.html
Labels: bug, enhancement, front-end

#18 Fixed Full Gantt Viewer
  Code_Gantt.js
Labels: bug, front-end
